# Generated by Django 5.2.3 on 2025-06-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='desrcription',
            new_name='description',
        ),
    ]
